package org.hyperscala.html.event

import org.hyperscala.javascript.JavaScriptContent
import org.powerscala.property.PropertyParent
import org.hyperscala.PropertyAttribute

/**
 * @author Matt Hicks <mhicks@powerscala.org>
 */
trait EventSupport extends PropertyParent {
  object event {
    val afterPrint = PropertyAttribute[JavaScriptContent]("onbeforeprint", null)
    val beforePrint = PropertyAttribute[JavaScriptContent]("onbeforeprint", null)
    val beforeOnLoad = PropertyAttribute[JavaScriptContent]("onbeforeonload", null)
    val hasChange = PropertyAttribute[JavaScriptContent]("onhaschange", null)
    val load = PropertyAttribute[JavaScriptContent]("onload", null)
    val message = PropertyAttribute[JavaScriptContent]("onmessage", null)
    val offline = PropertyAttribute[JavaScriptContent]("onoffline", null)
    val online = PropertyAttribute[JavaScriptContent]("ononline", null)
    val pageHide = PropertyAttribute[JavaScriptContent]("onpagehide", null)
    val pageShow = PropertyAttribute[JavaScriptContent]("onpageshow", null)
    val popState = PropertyAttribute[JavaScriptContent]("onpopstate", null)
    val redo = PropertyAttribute[JavaScriptContent]("onredo", null)
    val resize = PropertyAttribute[JavaScriptContent]("onresize", null)
    val storage = PropertyAttribute[JavaScriptContent]("onstorage", null)
    val undo = PropertyAttribute[JavaScriptContent]("onundo", null)
    val unLoad = PropertyAttribute[JavaScriptContent]("onunload", null)
    val blur = PropertyAttribute[JavaScriptContent]("onblur", null)
    val change = PropertyAttribute[JavaScriptContent]("onchange", null)
    val contextMenu = PropertyAttribute[JavaScriptContent]("oncontextmenu", null)
    val focus = PropertyAttribute[JavaScriptContent]("onfocus", null)
    val formChange = PropertyAttribute[JavaScriptContent]("onformchange", null)
    val formInput = PropertyAttribute[JavaScriptContent]("onforminput", null)
    val input = PropertyAttribute[JavaScriptContent]("oninput", null)
    val invalid = PropertyAttribute[JavaScriptContent]("oninvalid", null)
    val reset = PropertyAttribute[JavaScriptContent]("onreset", null)
    val select = PropertyAttribute[JavaScriptContent]("onselect", null)
    val submit = PropertyAttribute[JavaScriptContent]("onsubmit", null)
    val keyDown = PropertyAttribute[JavaScriptContent]("onkeydown", null)
    val keyPress = PropertyAttribute[JavaScriptContent]("onkeypress", null)
    val keyUp = PropertyAttribute[JavaScriptContent]("onkeyup", null)
    val click = PropertyAttribute[JavaScriptContent]("onclick", null)
    val doubleClick = PropertyAttribute[JavaScriptContent]("ondblclick", null)
    val drag = PropertyAttribute[JavaScriptContent]("ondrag", null)
    val dragEnd = PropertyAttribute[JavaScriptContent]("ondragend", null)
    val dragEnter = PropertyAttribute[JavaScriptContent]("ondragenter", null)
    val dragLeave = PropertyAttribute[JavaScriptContent]("ondragleave", null)
    val dragOver = PropertyAttribute[JavaScriptContent]("ondragover", null)
    val dragStart = PropertyAttribute[JavaScriptContent]("ondragstart", null)
    val drop = PropertyAttribute[JavaScriptContent]("ondrop", null)
    val mouseDown = PropertyAttribute[JavaScriptContent]("onmousedown", null)
    val mouseMove = PropertyAttribute[JavaScriptContent]("onmousemove", null)
    val mouseOut = PropertyAttribute[JavaScriptContent]("onmouseout", null)
    val mouseOver = PropertyAttribute[JavaScriptContent]("onmouseover", null)
    val mouseUp = PropertyAttribute[JavaScriptContent]("onmouseup", null)
    val mouseWheel = PropertyAttribute[JavaScriptContent]("onmousewheel", null)
    val scroll = PropertyAttribute[JavaScriptContent]("onscroll", null)
    val abort = PropertyAttribute[JavaScriptContent]("onabort", null)
    val canPlay = PropertyAttribute[JavaScriptContent]("oncanplay", null)
    val canPlayThrough = PropertyAttribute[JavaScriptContent]("oncanplaythrough", null)
    val durationChange = PropertyAttribute[JavaScriptContent]("ondurationchange", null)
    val emptied = PropertyAttribute[JavaScriptContent]("onemptied", null)
    val ended = PropertyAttribute[JavaScriptContent]("onended", null)
    val error = PropertyAttribute[JavaScriptContent]("onerror", null)
    val loadedData = PropertyAttribute[JavaScriptContent]("onloadeddata", null)
    val loadedMetaData = PropertyAttribute[JavaScriptContent]("onloadedmetadata", null)
    val loadStart = PropertyAttribute[JavaScriptContent]("onloadstart", null)
    val pause = PropertyAttribute[JavaScriptContent]("onpause", null)
    val play = PropertyAttribute[JavaScriptContent]("onplay", null)
    val playing = PropertyAttribute[JavaScriptContent]("onplaying", null)
    val progress = PropertyAttribute[JavaScriptContent]("onprogress", null)
    val rateChange = PropertyAttribute[JavaScriptContent]("onratechange", null)
    val readyStateChange = PropertyAttribute[JavaScriptContent]("onreadystatechange", null)
    val seeked = PropertyAttribute[JavaScriptContent]("onseeked", null)
    val seeking = PropertyAttribute[JavaScriptContent]("onseeking", null)
    val stalled = PropertyAttribute[JavaScriptContent]("onstalled", null)
    val suspend = PropertyAttribute[JavaScriptContent]("onsuspend", null)
    val timeUpdate = PropertyAttribute[JavaScriptContent]("ontimeupdate", null)
    val volumeChange = PropertyAttribute[JavaScriptContent]("onvolumechange", null)
    val waiting = PropertyAttribute[JavaScriptContent]("onwaiting", null)
  }
}