package org.hyperscala.web.live

import org.hyperscala.javascript.JavaScriptString
import org.hyperscala.html.HTMLTag
import org.powerscala.event.Event

/**
 * @author Matt Hicks <mhicks@powerscala.org>
 */
class LiveEvent(tag: HTMLTag) extends Event

object LiveEvent extends JavaScriptString("liveEventHandler(event); return false;") {
  def confirm(message: String) = {
    JavaScriptString("if (confirm('%s')) { liveEventHandler(event); } return false;".format(LivePage.escape(message)))
  }

  def apply(tag: HTMLTag, eventType: String) = eventType match {
    case "afterprint" => new AfterPrintEvent(tag)
    case "beforeprint" => new BeforePrintEvent(tag)
    case "beforeonload" => new BeforeOnLoadEvent(tag)
    case "haschange" => new HasChangeEvent(tag)
    case "load" => new LoadEvent(tag)
    case "message" => new MessageEvent(tag)
    case "offline" => new OfflineEvent(tag)
    case "online" => new OnlineEvent(tag)
    case "pagehide" => new PageHideEvent(tag)
    case "pageshow" => new PageShowEvent(tag)
    case "popstate" => new PopStateEvent(tag)
    case "redo" => new RedoEvent(tag)
    case "resize" => new ResizeEvent(tag)
    case "storage" => new StorageEvent(tag)
    case "undo" => new UndoEvent(tag)
    case "unload" => new UnLoadEvent(tag)
    case "blur" => new BlurEvent(tag)
    case "change" => new ChangeEvent(tag)
    case "contextmenu" => new ContextMenuEvent(tag)
    case "focus" => new FocusEvent(tag)
    case "formchange" => new FormChangeEvent(tag)
    case "forminput" => new FormInputEvent(tag)
    case "input" => new InputEvent(tag)
    case "invalid" => new InvalidEvent(tag)
    case "reset" => new ResetEvent(tag)
    case "select" => new SelectEvent(tag)
    case "submit" => new SubmitEvent(tag)
    case "keydown" => new KeyDownEvent(tag)
    case "keypress" => new KeyPressEvent(tag)
    case "keyup" => new KeyUpEvent(tag)
    case "click" => new ClickEvent(tag)
    case "dblclick" => new DoubleClickEvent(tag)
    case "drag" => new DragEvent(tag)
    case "dragend" => new DragEndEvent(tag)
    case "dragenter" => new DragEnterEvent(tag)
    case "dragleave" => new DragLeaveEvent(tag)
    case "dragover" => new DragOverEvent(tag)
    case "dragstart" => new DragStartEvent(tag)
    case "drop" => new DropEvent(tag)
    case "mousedown" => new MouseDownEvent(tag)
    case "mousemove" => new MouseMoveEvent(tag)
    case "mouseout" => new MouseOutEvent(tag)
    case "mouseover" => new MouseOverEvent(tag)
    case "mouseup" => new MouseUpEvent(tag)
    case "mousewheel" => new MouseWheelEvent(tag)
    case "scroll" => new ScrollEvent(tag)
    case "abort" => new AbortEvent(tag)
    case "canplay" => new CanPlayEvent(tag)
    case "canplaythrough" => new CanPlayThroughEvent(tag)
    case "durationchange" => new DurationChangeEvent(tag)
    case "emptied" => new EmptiedEvent(tag)
    case "ended" => new EndedEvent(tag)
    case "error" => new ErrorEvent(tag)
    case "loadeddata" => new LoadedDataEvent(tag)
    case "loadedmetadata" => new LoadedMetaDataEvent(tag)
    case "loadstart" => new LoadStartEvent(tag)
    case "pause" => new PauseEvent(tag)
    case "play" => new PlayEvent(tag)
    case "playing" => new PlayingEvent(tag)
    case "progress" => new ProgressEvent(tag)
    case "ratechange" => new RateChangeEvent(tag)
    case "readystatechange" => new ReadyStateChangeEvent(tag)
    case "seeked" => new SeekedEvent(tag)
    case "seeking" => new SeekingEvent(tag)
    case "stalled" => new StalledEvent(tag)
    case "suspend" => new SuspendEvent(tag)
    case "timeupdate" => new TimeUpdateEvent(tag)
    case "volumechange" => new VolumeChangeEvent(tag)
    case "waiting" => new WaitingEvent(tag)
  }
}

class AfterPrintEvent(tag: HTMLTag) extends LiveEvent(tag)
class BeforePrintEvent(tag: HTMLTag) extends LiveEvent(tag)
class BeforeOnLoadEvent(tag: HTMLTag) extends LiveEvent(tag)
class HasChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class LoadEvent(tag: HTMLTag) extends LiveEvent(tag)
class MessageEvent(tag: HTMLTag) extends LiveEvent(tag)
class OfflineEvent(tag: HTMLTag) extends LiveEvent(tag)
class OnlineEvent(tag: HTMLTag) extends LiveEvent(tag)
class PageHideEvent(tag: HTMLTag) extends LiveEvent(tag)
class PageShowEvent(tag: HTMLTag) extends LiveEvent(tag)
class PopStateEvent(tag: HTMLTag) extends LiveEvent(tag)
class RedoEvent(tag: HTMLTag) extends LiveEvent(tag)
class ResizeEvent(tag: HTMLTag) extends LiveEvent(tag)
class StorageEvent(tag: HTMLTag) extends LiveEvent(tag)
class UndoEvent(tag: HTMLTag) extends LiveEvent(tag)
class UnLoadEvent(tag: HTMLTag) extends LiveEvent(tag)
class BlurEvent(tag: HTMLTag) extends LiveEvent(tag)
class ChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class ContextMenuEvent(tag: HTMLTag) extends LiveEvent(tag)
class FocusEvent(tag: HTMLTag) extends LiveEvent(tag)
class FormChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class FormInputEvent(tag: HTMLTag) extends LiveEvent(tag)
class InputEvent(tag: HTMLTag) extends LiveEvent(tag)
class InvalidEvent(tag: HTMLTag) extends LiveEvent(tag)
class ResetEvent(tag: HTMLTag) extends LiveEvent(tag)
class SelectEvent(tag: HTMLTag) extends LiveEvent(tag)
class SubmitEvent(tag: HTMLTag) extends LiveEvent(tag)
class KeyDownEvent(tag: HTMLTag) extends LiveEvent(tag)
class KeyPressEvent(tag: HTMLTag) extends LiveEvent(tag)
class KeyUpEvent(tag: HTMLTag) extends LiveEvent(tag)
class ClickEvent(tag: HTMLTag) extends LiveEvent(tag)
class DoubleClickEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragEndEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragEnterEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragLeaveEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragOverEvent(tag: HTMLTag) extends LiveEvent(tag)
class DragStartEvent(tag: HTMLTag) extends LiveEvent(tag)
class DropEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseDownEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseMoveEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseOutEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseOverEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseUpEvent(tag: HTMLTag) extends LiveEvent(tag)
class MouseWheelEvent(tag: HTMLTag) extends LiveEvent(tag)
class ScrollEvent(tag: HTMLTag) extends LiveEvent(tag)
class AbortEvent(tag: HTMLTag) extends LiveEvent(tag)
class CanPlayEvent(tag: HTMLTag) extends LiveEvent(tag)
class CanPlayThroughEvent(tag: HTMLTag) extends LiveEvent(tag)
class DurationChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class EmptiedEvent(tag: HTMLTag) extends LiveEvent(tag)
class EndedEvent(tag: HTMLTag) extends LiveEvent(tag)
class ErrorEvent(tag: HTMLTag) extends LiveEvent(tag)
class LoadedDataEvent(tag: HTMLTag) extends LiveEvent(tag)
class LoadedMetaDataEvent(tag: HTMLTag) extends LiveEvent(tag)
class LoadStartEvent(tag: HTMLTag) extends LiveEvent(tag)
class PauseEvent(tag: HTMLTag) extends LiveEvent(tag)
class PlayEvent(tag: HTMLTag) extends LiveEvent(tag)
class PlayingEvent(tag: HTMLTag) extends LiveEvent(tag)
class ProgressEvent(tag: HTMLTag) extends LiveEvent(tag)
class RateChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class ReadyStateChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class SeekedEvent(tag: HTMLTag) extends LiveEvent(tag)
class SeekingEvent(tag: HTMLTag) extends LiveEvent(tag)
class StalledEvent(tag: HTMLTag) extends LiveEvent(tag)
class SuspendEvent(tag: HTMLTag) extends LiveEvent(tag)
class TimeUpdateEvent(tag: HTMLTag) extends LiveEvent(tag)
class VolumeChangeEvent(tag: HTMLTag) extends LiveEvent(tag)
class WaitingEvent(tag: HTMLTag) extends LiveEvent(tag)